/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Approvals: () => import('#controllers/approvals_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Tasks: () => import('#controllers/tasks_controller'),
}
