import { writeFile, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'
import { unixSocketRequest } from '#services/egress/unix_socket_client'

/**
 * Phase 8a: write a per-team Outcall rule pack to disk and ask the
 * daemon to reload. Generates the same shape as
 * `outcall-presets/presets/clawie-default.yaml`, but with the
 * `agent.name` pattern scoped to the team:
 *
 *   agent.name == "clawie-<team-slug>-chat"
 *
 * Two assumptions on the deployment:
 *   1. The clawie process can write to /etc/outcall/rules.d/. In
 *      containerised deployments this typically means a host-path
 *      mount; if it can't, this throws and the operator gets a clear
 *      error.
 *   2. The reload endpoint at /run/outcall/host.sock is reachable.
 *      Same socket as the OutcallApiClient uses.
 *
 * Rules are intentionally scoped narrowly: chat → anthropic + openai
 * only. Operators who want broader access edit the file by hand and
 * pin their version in their own outcall-presets fork.
 */

const RULES_DIR = '/etc/outcall/rules.d'
const HOST_SOCKET = '/run/outcall/host.sock'

export interface TeamRulePack {
  teamSlug: string
  /** Provider hosts the team's chat intent may reach. */
  allowedChatHosts?: string[]
}

export interface SyncResult {
  filePath: string
  bytesWritten: number
  reloaded: { filesLoaded: number; rulesLoaded: number; warnings: string[] }
}

export interface RulePackWriterOptions {
  rulesDir?: string
  hostSocketPath?: string
}

export class RulePackWriter {
  private readonly rulesDir: string
  private readonly hostSocketPath: string

  constructor(opts: RulePackWriterOptions = {}) {
    this.rulesDir = opts.rulesDir ?? RULES_DIR
    this.hostSocketPath = opts.hostSocketPath ?? HOST_SOCKET
  }

  async syncTeam(pack: TeamRulePack): Promise<SyncResult> {
    if (!/^[a-z0-9][a-z0-9-]{0,62}$/.test(pack.teamSlug)) {
      throw new Error(`invalid team slug: ${pack.teamSlug}`)
    }
    const hosts = pack.allowedChatHosts ?? ['api.anthropic.com', 'api.openai.com']
    const yaml = renderYaml(pack.teamSlug, hosts)
    const filePath = `${this.rulesDir}/clawie-team-${pack.teamSlug}.yaml`
    await mkdir(dirname(filePath), { recursive: true })
    await writeFile(filePath, yaml, 'utf8')

    const res = await unixSocketRequest(this.hostSocketPath, '/api/v1/rules/reload', {
      method: 'POST',
      json: {},
    })
    if (res.status !== 200) {
      throw new Error(`rules reload returned HTTP ${res.status}: ${res.body.slice(0, 200)}`)
    }
    const env = JSON.parse(res.body) as {
      success: boolean
      data?: { files_loaded: number; rules_loaded: number; warnings: string[] }
      error?: string
    }
    if (!env.success || !env.data) {
      throw new Error(`rules reload envelope.success=false: ${env.error ?? 'no detail'}`)
    }
    return {
      filePath,
      bytesWritten: Buffer.byteLength(yaml, 'utf8'),
      reloaded: {
        filesLoaded: env.data.files_loaded,
        rulesLoaded: env.data.rules_loaded,
        warnings: env.data.warnings,
      },
    }
  }
}

function renderYaml(teamSlug: string, hosts: string[]): string {
  const header = `# Generated by clawie's RulePackWriter. Edit at your own risk -- next
# sync overwrites it. Team slug: ${teamSlug}.

version: "1"

rules:`
  const blocks = hosts.map((host, idx) => {
    // Slug the full host so two hosts sharing a registrable domain
    // (api.anthropic.com vs eu.anthropic.com) get distinct rule ids.
    const hostSlug = host
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
    const id = `clawie-team-${teamSlug}-chat-${hostSlug}`
    const cond = `agent.name == "clawie-${teamSlug}-chat" && (dns.query == "${host}" || http.host == "${host}")`
    return [
      `  - id: ${id}`,
      `    description: "Team ${teamSlug} chat -> ${host}"`,
      `    condition: '${cond}'`,
      `    action: allow`,
      `    priority: ${100 + idx}`,
      `    egress:`,
      `      mode: proxy`,
    ].join('\n')
  })
  return `${header}\n${blocks.join('\n\n')}\n`
}
